---
abstract: 'Extended MicroTemplate'
author:
  - 'Daisuke Murase <typester@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Base: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.97'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-MicroTemplate-Extended
no_index:
  directory:
    - example
    - inc
    - t
requires:
  Text::MicroTemplate: 0.13
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/typester/text-microtemplate-extended-perl.git
version: 0.11
